apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs
  labels: 
    app: nodejs
spec:
  replicas: 3
  selector:
    matchlabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      nodeSelector:
        "beta.kubenetes.io/os": linux
      containers:
        - name: nodejs-aks-app
          image: nodejs-aks-app
          ports:
            - name: http
              containerPort: 1337